name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-and-fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: alsa
      run: sudo apt-get install -y alsa-utils
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Fmt
      run: cargo fmt --check
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: alsa
      run: sudo apt-get install -y alsa-utils
    - name: Run tests
      run: cargo test --verbose
